# Generated by Django 5.1.1 on 2025-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
