# Generated by Django 5.1.1 on 2025-03-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_devicehistory_last_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceHistory',
        ),
    ]
