# Generated by Django 5.1.1 on 2024-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_remove_user_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
