# Generated by Django 5.1.1 on 2024-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
