# Generated by Django 5.1.1 on 2024-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0007_userprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kyc_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_images/'),
        ),
    ]
