# Generated by Django 5.1.1 on 2024-11-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0008_userprofile_kyc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kyc_image',
        ),
    ]
