# Generated by Django 5.1.1 on 2024-11-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0010_userprofile_kyc_image_userprofile_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
