# Generated by Django 5.1.1 on 2024-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0011_alter_userprofile_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kyc_window_shown',
            field=models.BooleanField(default=False),
        ),
    ]
