# Generated by Django 5.0.2 on 2024-12-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0012_userprofile_kyc_window_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
