# Generated by Django 5.1.5 on 2025-02-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0015_userprofile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
