# Generated by Django 5.1.7 on 2025-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0017_userprivacy_address_userprivacy_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicehistory',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
