# Generated by Django 5.1.7 on 2025-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0018_userdevicehistory_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacy',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile-photos/default-profile.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
