# Generated by Django 5.1.7 on 2025-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0019_alter_userprivacy_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacy',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
