# Generated by Django 5.0.6 on 2025-04-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0020_alter_userprivacy_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
