# Generated by Django 5.1.1 on 2025-03-01 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0022_alter_admin_dashboard_preview_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_at', models.DateTimeField(blank=True, null=True)),
                ('payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('lottery_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lotteries', to='adminpanel.lotteryevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lotteries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
