# Generated by Django 5.1.1 on 2025-03-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0002_paymentlottery_receipt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlottery',
            name='receipt_url',
        ),
    ]
