# Generated by Django 5.1.1 on 2025-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0003_remove_paymentlottery_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlottery',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
