# Generated by Django 5.1.1 on 2025-03-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0004_paymentlottery_receipt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlottery',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
