# Generated by Django 5.1.1 on 2025-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0006_alter_paymentlottery_receipt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlottery',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
