# Generated by Django 5.1.1 on 2025-03-15 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0007_alter_paymentlottery_payment_status'),
        ('adminpanel', '0022_alter_admin_dashboard_preview_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=6, unique=True)),
                ('lottery_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_tickets', to='adminpanel.lotteryevent')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_tickets', to='PaymentServices.paymentlottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
