# Generated by Django 5.1.1 on 2024-11-28 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('draw_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lottery_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('sold_percentage', models.PositiveIntegerField(default=0)),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('sold_tickets', models.PositiveIntegerField(default=0)),
                ('mini_limit', models.PositiveIntegerField(default=1)),
                ('max_limit', models.PositiveIntegerField(default=10)),
                ('free_postal_description', models.TextField(default='Enter the description for free postal entry.')),
            ],
        ),
        migrations.CreateModel(
            name='adminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('', 'Select Role'), ('admin', 'Admin')], default='', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
