# Generated by Django 5.1.1 on 2024-11-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryevent',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
