# Generated by Django 5.1.1 on 2024-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_lotteryevent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryevent',
            name='per_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lotteryevent',
            name='revenue_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=50),
        ),
        migrations.AddField(
            model_name='lotteryevent',
            name='revenue_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lotteryevent',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lotteryevent',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
