# Generated by Django 5.1.1 on 2024-12-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_lotteryevent_per_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryevent',
            name='competition_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lotteryevent',
            name='faq',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='LotteryEventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lottery_event_additional_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lottery_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='adminpanel.lotteryevent')),
            ],
        ),
    ]
