# Generated by Django 5.1.1 on 2024-12-10 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_lotteryevent_competition_details_lotteryevent_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_dashboard_preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tab name to display', max_length=100)),
                ('identifier', models.CharField(help_text='Unique identifier for this container (used in frontend)', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('count', 'count'), ('table', 'Table'), ('rate', 'rate')], default='count', help_text='Type of content: card or table', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='admin_navbar_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_physical', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'Select Role'), ('admin', 'Admin'), ('sales', 'Sales')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='dashboard_preview',
            field=models.ManyToManyField(blank=True, to='adminpanel.admin_dashboard_preview'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='navbar_access',
            field=models.ManyToManyField(blank=True, to='adminpanel.admin_navbar_access'),
        ),
        migrations.CreateModel(
            name='TicketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_sold', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=True)),
                ('lottery_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='adminpanel.lotteryevent')),
            ],
        ),
    ]
