# Generated by Django 5.0.2 on 2024-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_admin_dashboard_preview_admin_navbar_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotteryevent',
            name='faq',
        ),
        migrations.AlterField(
            model_name='lotteryevent',
            name='competition_details',
            field=models.TextField(default=''),
        ),
    ]
