# Generated by Django 5.0.2 on 2024-12-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('count', 'count'), ('table', 'Table'), ('rate', 'rate'), ('lotterys', 'lotterys')], default='', help_text='Type of content', max_length=10),
        ),
    ]
