# Generated by Django 5.0.2 on 2024-12-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_lotterycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryevent',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lottery_events', to='adminpanel.lotterycategory'),
        ),
    ]
