# Generated by Django 5.0.6 on 2025-01-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_lotteryevent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='admin_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adminpanel.contact')),
            ],
        ),
    ]
