# Generated by Django 5.1.1 on 2025-01-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_winner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Winner',
            new_name='Previous_Winner_img',
        ),
    ]
