# Generated by Django 5.1.1 on 2025-01-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_rename_winner_previous_winner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
