# Generated by Django 5.1.1 on 2025-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_banner_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show_explore_button',
            field=models.BooleanField(default=True),
        ),
    ]
