# Generated by Django 5.1.1 on 2025-01-22 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_banner_show_explore_button'),
        ('user_registration', '0013_userprofile_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='lottery_sales_bar_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
                ('activity_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('won_lottery', models.IntegerField(default=0)),
                ('lost_lottery', models.IntegerField(default=0)),
                ('won_percentage', models.FloatField(default=0.0)),
                ('current_won_percentage', models.FloatField(default=0.0)),
                ('lost_percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='admin_navbar_access',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('count', 'count'), ('Statistics_count', 'Statistics_count'), ('table', 'Table'), ('rate', 'rate'), ('lotterys', 'lotterys'), ('lottery_sales_overview', 'lottery_sales_overview'), ('user_leaderboard', 'user_leaderboard')], default='', help_text='Type of content', max_length=30),
        ),
        migrations.AlterField(
            model_name='admin_navbar_access',
            name='url_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('correct_percentage', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lottery_image/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_registration.userprofile')),
            ],
        ),
    ]
