# Generated by Django 5.0.2 on 2025-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterycategory',
            name='category_logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='category_logos/'),
        ),
    ]
