# Generated by Django 5.0.6 on 2025-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_lotterycategory_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('total_sales', models.FloatField()),
                ('average', models.FloatField()),
                ('return_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('win_lottery', models.FloatField()),
                ('lost_lottery', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin_navbar_access',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='admin_dashboard_preview',
            name='dashboard_preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_preview_image/'),
        ),
        migrations.AddField(
            model_name='admin_navbar_access',
            name='nav_bar_image',
            field=models.ImageField(blank=True, null=True, upload_to='navbar_images/'),
        ),
        migrations.AddField(
            model_name='admin_navbar_access',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('count', 'count'), ('Statistics_count', 'Statistics_count'), ('table', 'Table'), ('rate', 'rate'), ('lotterys', 'lotterys'), ('lottery_sales_overview', 'lottery_sales_overview'), ('user_leaderboard', 'user_leaderboard'), ('lottery_sales_overview_regional_reports', 'lottery_sales_overview_regional_reports'), ('overview_counts', 'overview_counts')], default='', help_text='Type of content', max_length=100),
        ),
    ]
