# Generated by Django 5.1.5 on 2025-02-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_location_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('count', 'count'), ('Statistics_count', 'Statistics_count'), ('table', 'Table'), ('rate', 'rate'), ('lotterys', 'lotterys'), ('lottery_sales_overview', 'lottery_sales_overview'), ('user_leaderboard', 'user_leaderboard'), ('lottery_sales_overview_regional_reports', 'lottery_sales_overview_regional_reports'), ('overview_counts', 'overview_counts'), ('overview_notification_bell', 'overview_notification_bell')], default='', help_text='Type of content', max_length=100),
        ),
    ]
