# Generated by Django 5.1.1 on 2025-03-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
