# Generated by Django 5.1.1 on 2025-03-18 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0008_lotteryticket'),
        ('adminpanel', '0024_delete_winner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=6, unique=True)),
                ('selected_method', models.CharField(choices=[('method1', '35-40 tickets'), ('method2', 'Highest purchase')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lottery_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='adminpanel.lotteryevent')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='PaymentServices.paymentlottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
