# Generated by Django 5.1.1 on 2025-03-18 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0008_lotteryticket'),
        ('adminpanel', '0025_winner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='selected_method',
        ),
        migrations.AddField(
            model_name='winner',
            name='selection_method',
            field=models.CharField(choices=[('method1', 'Random from 35-40 tickets'), ('method2', 'Highest purchase history')], default='method1', max_length=10),
        ),
        migrations.AlterField(
            model_name='winner',
            name='lottery_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.lotteryevent'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaymentServices.paymentlottery'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='ticket_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
