# Generated by Django 5.1.1 on 2025-03-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentServices', '0008_lotteryticket'),
        ('adminpanel', '0026_remove_winner_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PaymentServices.paymentlottery'),
        ),
    ]
