# Generated by Django 5.1.1 on 2025-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_alter_winner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='selection_method',
            field=models.CharField(choices=[('method1', 'Random from 35-40 tickets'), ('method2', 'Highest purchase history'), ('method3', 'range choosen')], default='method1', max_length=10),
        ),
    ]
