# Generated by Django 5.1.1 on 2025-03-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_alter_winner_selection_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='selection_method',
            field=models.CharField(choices=[('method1', 'Random purchsed  tickets'), ('method2', 'Highest purchases ticket '), ('method3', 'range choosen')], default='method1', max_length=10),
        ),
    ]
