# Generated by Django 5.1.1 on 2025-03-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_publishotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishOTP',
        ),
    ]
