# Generated by Django 5.1.1 on 2025-03-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0036_adminotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminOTP',
        ),
    ]
