# Generated by Django 5.0.6 on 2025-03-28 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_adminotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winner',
            name='prize_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='prize_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='prize_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='initiated', max_length=20),
        ),
    ]
