# Generated by Django 5.0.6 on 2025-03-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_winner_created_at_winner_prize_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryevent',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
