# Generated by Django 5.1.7 on 2025-04-15 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_alter_lotteryevent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
