# Generated by Django 5.0.6 on 2025-04-21 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_alter_winner_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnersWallWinnersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_name', models.CharField(max_length=150)),
                ('ticket_number', models.CharField(max_length=6)),
                ('lottery_name', models.CharField(max_length=255)),
                ('draw_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='winners_wall_photos/')),
                ('flag', models.BooleanField(default=True, help_text='Toggle to show/hide winner on the wall')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-draw_date'],
            },
        ),
    ]
