# Generated by Django 5.0.6 on 2025-05-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_winnerswallwinnerslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='identifier',
            field=models.CharField(help_text='Unique identifier for this container (used in frontend)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('charts', 'charts'), ('count', 'count'), ('Statistics_count', 'Statistics_count'), ('table', 'Table'), ('rate', 'rate'), ('lotterys', 'lotterys'), ('user_leaderboard', 'user_leaderboard'), ('lottery_sales_overview_regional_reports', 'lottery_sales_overview_regional_reports'), ('overview_counts', 'overview_counts'), ('overview_notification_bell', 'overview_notification_bell')], default='', help_text='Type of content', max_length=100),
        ),
    ]
