# Generated by Django 5.0.6 on 2025-05-22 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_alter_admin_dashboard_preview_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotteryevent',
            options={'ordering': ['-draw_date']},
        ),
        migrations.AddField(
            model_name='lotteryevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('charts', 'charts'), ('count', 'count'), ('Statistics_count', 'Statistics_count'), ('table', 'Table'), ('rate', 'rate'), ('lotterys', 'lotterys'), ('user_leaderboard', 'user_leaderboard'), ('overview_counts', 'overview_counts'), ('overview_notification_bell', 'overview_notification_bell')], default='', help_text='Type of content', max_length=100),
        ),
    ]
