# Generated by Django 5.1.1 on 2025-06-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0044_alter_lotteryevent_options_lotteryevent_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversionRate',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='lottery_sales_bar_chart',
        ),
        migrations.DeleteModel(
            name='LotteryStatistics',
        ),
        migrations.DeleteModel(
            name='RegionalSales',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RemoveField(
            model_name='tickettransaction',
            name='lottery_event',
        ),
        migrations.AlterModelOptions(
            name='admin_dashboard_preview',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='admin_dashboard_preview',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('charts', 'charts'), ('Statistics_count', 'Statistics_count'), ('table', 'Table'), ('transactions', 'transactions'), ('lotterys', 'lotterys'), ('overview_counts', 'overview_counts'), ('overview_notification_bell', 'overview_notification_bell')], default='', help_text='Type of content', max_length=100),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='TicketTransaction',
        ),
    ]
