# Generated by Django 5.1.1 on 2025-07-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_delete_conversionrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('charts', 'charts'), ('Statistics_count', 'Statistics_count'), ('user_management_table', 'user_management_table'), ('transactions', 'transactions'), ('lotterys', 'lotterys'), ('overview_counts', 'overview_counts'), ('user_chats_and_notification_bell_icon', 'user_chats_and_notification_bell_icon')], default='', help_text='Type of content', max_length=100),
        ),
    ]
