# Generated by Django 5.1.1 on 2025-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_alter_admin_dashboard_preview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_dashboard_preview',
            name='type',
            field=models.CharField(choices=[(' ', 'Select type'), ('charts', 'charts'), ('Statistics_count', 'Statistics_count'), ('user_management_table', 'user_management_table'), ('lotterys', 'lotterys'), ('overview_counts', 'overview_counts'), ('user_chats_and_notification_bell_icon', 'user_chats_and_notification_bell_icon')], default='', help_text='Type of content', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='winnerswallwinnerslist',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to='winners_wall_photos/'),
        ),
    ]
