# Generated by Django 5.1.1 on 2025-07-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0047_alter_admin_dashboard_preview_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'Select Role'), ('admin', 'Admin')], default='', max_length=12),
        ),
    ]
