# Generated by Django 5.1.1 on 2025-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_alter_adminprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryevent',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
